gen3:
  profile: bridge2ai
  project_id: bridge2ai-CM4AI
  version: null
log:
  format: '[%(asctime)s] [%(levelname)s] %(name)s %(message)s'
  level: INFO
output:
  format: yaml
state_dir: .g3t/state
