#!/bin/bash

# List of directories
dirs=("projects/bridge2ai-AI_READI" "projects/bridge2ai-CHoRUS" "projects/bridge2ai-CM4AI" "projects/bridge2ai-Voice")

# Save the current directory
start_dir=$(pwd)

# Command to execute
cmd="g3t_synapse_sync teams ls -l"

# Loop over directories
for dir in "${dirs[@]}"; do
  # Change to directory
  cd "$dir" || continue

  # Execute command
  $cmd
   # Return to the start directory
  cd "$start_dir"
done